let faq = document.querySelector('.faq-box')
let faq2 = document.querySelector('.faq-box2')
let faq3 = document.querySelector('.faq-box3')
let faq4 = document.querySelector('.faq-box4')
let faq5 = document.querySelector('.faq-box5')
let faq6 = document.querySelector('.faq-box6')
let faq7 = document.querySelector('.faq-box7')
let faq8 = document.querySelector('.faq-box8')
let faq9 = document.querySelector('.faq-box9')
let faq10 = document.querySelector('.faq-box10')

faq.addEventListener('click',()=>{
    faq.classList.toggle('abrir')
    faq2.classList.remove('abrir')
    faq3.classList.remove('abrir')
    faq4.classList.remove('abrir')
    faq5.classList.remove('abrir')
    faq6.classList.remove('abrir')
    faq7.classList.remove('abrir')
    faq8.classList.remove('abrir')
    faq9.classList.remove('abrir')
    faq10.classList.remove('abrir')
})
faq2.addEventListener('click',()=>{
    faq2.classList.toggle('abrir')
    faq.classList.remove('abrir')
    faq3.classList.remove('abrir')
    faq4.classList.remove('abrir')
    faq5.classList.remove('abrir')
    faq6.classList.remove('abrir')
    faq7.classList.remove('abrir')
    faq8.classList.remove('abrir')
    faq9.classList.remove('abrir')
    faq10.classList.remove('abrir')
    
})
faq3.addEventListener('click',()=>{
    faq3.classList.toggle('abrir')
    faq.classList.remove('abrir')
    faq2.classList.remove('abrir')
    faq4.classList.remove('abrir')
    faq5.classList.remove('abrir')
    faq6.classList.remove('abrir')
    faq7.classList.remove('abrir')
    faq8.classList.remove('abrir')
    faq9.classList.remove('abrir')
    faq10.classList.remove('abrir')
})
faq4.addEventListener('click',()=>{
    faq4.classList.toggle('abrir')
    faq.classList.remove('abrir')
    faq3.classList.remove('abrir')
    faq2.classList.remove('abrir')
    faq5.classList.remove('abrir')
    faq6.classList.remove('abrir')
    faq7.classList.remove('abrir')
    faq8.classList.remove('abrir')
    faq9.classList.remove('abrir')
    faq10.classList.remove('abrir')
})
faq5.addEventListener('click',()=>{
    faq5.classList.toggle('abrir')
    faq.classList.remove('abrir')
    faq3.classList.remove('abrir')
    faq4.classList.remove('abrir')
    faq2.classList.remove('abrir')
    faq6.classList.remove('abrir')
    faq7.classList.remove('abrir')
    faq8.classList.remove('abrir')
    faq9.classList.remove('abrir')
    faq10.classList.remove('abrir')
})
faq6.addEventListener('click',()=>{
    faq6.classList.toggle('abrir')
    faq.classList.remove('abrir')
    faq3.classList.remove('abrir')
    faq4.classList.remove('abrir')
    faq5.classList.remove('abrir')
    faq2.classList.remove('abrir')
    faq7.classList.remove('abrir')
    faq8.classList.remove('abrir')
    faq9.classList.remove('abrir')
    faq10.classList.remove('abrir')
})
faq7.addEventListener('click',()=>{
    faq7.classList.toggle('abrir')
    faq.classList.remove('abrir')
    faq2.classList.remove('abrir')
    faq3.classList.remove('abrir')
    faq4.classList.remove('abrir')
    faq5.classList.remove('abrir')
    faq6.classList.remove('abrir')
    faq8.classList.remove('abrir')
    faq9.classList.remove('abrir')
    faq10.classList.remove('abrir')
})
faq8.addEventListener('click',()=>{
    faq8.classList.toggle('abrir')
    faq.classList.remove('abrir')
    faq2.classList.remove('abrir')
    faq3.classList.remove('abrir')
    faq4.classList.remove('abrir')
    faq5.classList.remove('abrir')
    faq6.classList.remove('abrir')
    faq7.classList.remove('abrir')
    faq9.classList.remove('abrir')
    faq10.classList.remove('abrir')
})
faq9.addEventListener('click',()=>{
    faq9.classList.toggle('abrir')
    faq.classList.remove('abrir')
    faq2.classList.remove('abrir')
    faq3.classList.remove('abrir')
    faq4.classList.remove('abrir')
    faq5.classList.remove('abrir')
    faq6.classList.remove('abrir')
    faq7.classList.remove('abrir')
    faq8.classList.remove('abrir')
    faq10.classList.remove('abrir')
})
faq10.addEventListener('click',()=>{
    faq10.classList.toggle('abrir')
    faq.classList.remove('abrir')
    faq2.classList.remove('abrir')
    faq3.classList.remove('abrir')
    faq4.classList.remove('abrir')
    faq5.classList.remove('abrir')
    faq6.classList.remove('abrir')
    faq7.classList.remove('abrir')
    faq8.classList.remove('abrir')
    faq9.classList.remove('abrir')
})

let abrirMais = document.getElementById('abrirMais')
let perguntasFaq = document.getElementById('perguntas-faq') 
abrirMais.innerText = 'Ver mais'

abrirMais.addEventListener('click',()=>{
    perguntasFaq.classList.toggle('ver')
    if(abrirMais.innerText === 'Ver mais'){
        abrirMais.innerText = 'Ver menos'
    }else{
        abrirMais.innerText = 'Ver mais'
    }
})
